name: Trigger Test

on:
  release:
    types: [published]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        repo: ['@zenstackhq/sample-todo-nextjs']
        
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          repository: ${{ matrix.repo }}
          event-type: zenstack-release
          
